services:
  - type: web
    name: mini-estufa-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - fromGroup: mini-estufa-shared
      - key: VITE_SUPABASE_HISTORY_TABLE
        value: leituras_formatadas


